### ISSUE TITLE
children outer width is returing object always in your js

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marekjalovec/jquery-infinite-carousel#22] opened 2015-05-15 16:45 UTC
```
This is the line where you put code to calculate children width in carousel.js.

var increment = jQuery(sliderList).children().outerWidth("true")

But problem is that it always return object with some jQuery older versions, 
true must be pass as Boolean not as string. 


What steps will reproduce the problem?
1. this should be like outerWidth(true)

```

Original issue reported on code.google.com by `letmethi...@gmail.com` on 10 Jul 2014 at 7:21

**Comment by marekjalovec** [comment] 2015-05-15 20:57
Duplicate of #23

**Closed by marekjalovec** 2015-05-15 20:57 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
