### ISSUE TITLE
It doesn't woks with recent jQuery

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marekjalovec/jquery-infinite-carousel#20] opened 2015-05-15 16:45 UTC
```
I can only make it work with the jQuery that comes with the plugin, but it is 
way outdated (1.3.2, current is 1.10.2).

jQuery 1.3.2 = Works
Latest jQuery = Bugged


```

Original issue reported on code.google.com by `lucasfbu...@gmail.com` on 13 Oct 2013 at 3:07

**Comment by marekjalovec** [comment] 2015-05-15 16:56
Duplicate of #23

**Closed by marekjalovec** 2015-05-15 16:56 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
