### ISSUE TITLE
Patch for /trunk/jquery.infinite-carousel.js

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marekjalovec/jquery-infinite-carousel#15] opened 2015-05-15 16:45 UTC
```
Made compatible with jQuery 1.8.2
jQuery(sliderList).children().outerWidth("true") replaced by
jQuery(sliderList).children().outerWidth(true)
Demo: http://jsfiddle.net/EhJrR/5/
```

Original issue reported on code.google.com by `bert.reg...@gmail.com` on 16 Nov 2012 at 10:10

Attachments:
* [jquery.infinite-carousel.js.patch](https://storage.googleapis.com/google-code-attachments/jquery-infinite-carousel/issue-15/comment-0/jquery.infinite-carousel.js.patch)

**Comment by marekjalovec** [comment] 2015-05-16 20:05
Duplicate of #23

**Closed by marekjalovec** 2015-05-16 20:05 UTC
Labels: auto-migrated, Type-Patch
