### ISSUE TITLE
Doesn't work with jquery-1.10.2.min.js

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marekjalovec/jquery-infinite-carousel#21] opened 2015-05-15 16:45 UTC
```
If I use infinite-carousel with http://code.jquery.com/jquery-1.10.2.min.js it 
won't work.

Fortunately the solution is simple. Just replace this line:
var increment = jQuery(sliderList).children().outerWidth("true"),

with this:

var increment = jQuery(sliderList).children().outerWidth(true),


So only the quotation marks were causing trouble.
```

Original issue reported on code.google.com by `flora.fi...@gmail.com` on 17 Feb 2014 at 1:52

**Comment by marekjalovec** [comment] 2015-05-15 16:53
Duplicate of #23

**Closed by marekjalovec** 2015-05-15 16:53 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
