### ISSUE TITLE
increment width outerWidth("true") - better with bool true

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marekjalovec/jquery-infinite-carousel#17] opened 2015-05-15 16:45 UTC
```
The jquery plugin sets the variable incremet with outerWidth and "true" as a 
string as the argument. This does not work for me. The return was an object, 
not the width as an integer. I changed it to true as a bool and now it works 
fine.

I used jQuery 1.8


```

Original issue reported on code.google.com by `timo.rue...@gmail.com` on 19 Jun 2013 at 11:28

**Comment by marekjalovec** [comment] 2015-05-15 16:53
Duplicate of #23

**Closed by marekjalovec** 2015-05-15 16:53 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
